apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tinta-issuer
  namespace: tinta
spec:
  acme:
    email: nelson.antunes994@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: tinta-key
    solvers:
    - dns01:
        cloudflare:
          email: nelson.antunes994@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-key
