name: Format
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  run_if:
    if: github.event.pull_request.base.ref != 'main'
    runs_on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'develop/'"
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  format:
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.17'
          cache: 'poetry' # caching pip dependencies
      - name: Install dependencies with poetry
        run: poetry install --without semver
      - name: pre-commit formatter
        uses: pre-commit/action@v3.0.0
