name: Format
on:
  push:
    branches:
      - main
      - develop
    pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  format:
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.17'
          cache: 'poetry' # caching pip dependencies
      - name: Install dependencies with poetry
        run: poetry install --without semver
      - name: pre-commit formatter
        uses: pre-commit/action@v3.0.0
  merge-main-back-to-dev:
    needs: release
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: Set Git Config
        run: |
          git config --local user.email "nelson.antunes994@gmail.com"
          git config --local user.name "nelsi11120"
      - name: Merge main back to develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff main -m "Auto-merge main back to develop"
          git push
