name: Format code
on:
  push:
    branches: ["main"]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.17'
          cache: 'poetry' # caching pip dependencies
      - name: Install dependencies with poetry
        run: poetry install
      - name: pre-commit formatter
        uses: pre-commit/action@v3.0.0
